pipeline {
  agent { 
    node {
      label "build"
    }
  }
  stages {
    stage("Git Checkout") {
            steps {
                checkout scm: [$class: 'GitSCM', userRemoteConfigs: [[url: "repo-url", credentialsId: "${git_users[JENKINS_ENVIRONMENT]}"]], branches: [[name: "${params.BRANCH}"]]]
            }
        }
    stage("Build microservice-1 artifact") {
      steps {
          script {
             dir("${WORKSPACE}/microservice-1") {
                  sh "mvn dependency:purge-local-repository"
                  sh "mvn clean deploy"
              }
            }
          }
      }
  }
   post {
        always {
            script {
                echo "Clean up our workspace"
                deleteDir() /* clean up our workspace, every little helps */
            }
        }
        failure {
            script {
                echo "The build has failed. Send out notifications!"
                def cause = getBuildCause()
                if (cause == 'user') {
                    emailext body: "Project: ${env.JOB_NAME} \n Build Number: ${env.BUILD_URL} has failed", recipientProviders: [[$class: 'DevelopersRecipientProvider'], [$class: 'RequesterRecipientProvider']], subject: "ERROR CI: Project name -> ${env.JOB_NAME}"
                }
                else {
                    echo "Triggered by Timer"
                    // Query the application_list table to get the notification end point for the application. It will be an workplace group.
                    // Run curl commands to send a message to the workplace group, identified in the above step.
                }
            }    
        }
    }
}
